### ISSUE TITLE
Publish on Open VSX registry

### ISSUE THREAD

**Issue by nicolas-brousse** [benspaulding/vscode-procfile#2]
VSCodium now use https://open-vsx.org/ as registry.

Do you plan to publish your extension on this registry?

They have a documentation about [publishing an extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension) and a [GitHub action](https://github.com/HaaLeo/publish-vscode-extension#readme) that help about publishing.

**Comment by benspaulding** [comment]
Done! https://open-vsx.org/extension/benspaulding/procfile

Thanks for letting me know about Open VSX.

**Comment by nicolas-brousse** [comment]
Thank you very mush for your extension and having added it on Open VSX
